name: chatbotapp
description: "A new Flutter project."
version: 1.0.0+1

environment:
  sdk: ">=3.4.1 <4.0.0"

dependencies:
  http: ^1.2.1
  cupertino_icons: ^1.0.6
  flutter:
    sdk: flutter
  flutter_dotenv: ^5.1.0
  flutter_markdown: ^0.7.2
  flutter_spinkit: ^5.2.1
  google_generative_ai: ^0.4.3
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  image_picker: ^1.1.2
  path_provider: ^2.1.3
  provider: ^6.1.2
  uuid: ^4.4.0
  shared_preferences: ^2.2.3
  country_pickers: ^3.0.1
  pinput: ^5.0.0
  rounded_loading_button: ^2.1.0
  html: ^0.15.4


  firebase_core: ^3.6.0
  firebase_auth: ^5.3.1
  firebase_storage: ^12.3.2
  google_sign_in: ^6.2.1
  cloud_firestore: ^5.4.4
  the_apple_sign_in: ^1.1.1
  firebase_ui_auth: ^1.15.0



dev_dependencies:
  build_runner: ^2.4.11
  flutter_lints: ^5.0.0

  

  flutter_test:
    sdk: flutter
  hive_generator: ^2.0.1

flutter:
  uses-material-design: true
  assets:
    - assets/images/
    - assets/screenshots/
  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware
  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages
  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  # fonts:
  #   - family: Schyler
  #     fonts:
  #       - asset: fonts/Schyler-Regular.ttf
  #       - asset: fonts/Schyler-Italic.ttf
  #         style: italic
  #   - family: Trajan Pro
  #     fonts:
  #       - asset: fonts/TrajanPro.ttf
  #       - asset: fonts/TrajanPro_Bold.ttf
  #         weight: 700
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
